//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Reservation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_train
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_train()
        {
            this.users = new HashSet<user>();
        }
    
        public int train_number { get; set; }
        public string train_name { get; set; }
        public string train_status { get; set; }
        public decimal ticket_price { get; set; }
        public int total_seats { get; set; }
        public int seats_available { get; set; }
        public string boarding_location { get; set; }
        public string drop_location { get; set; }
        public System.DateTime boarding_date { get; set; }
        public System.DateTime drop_date { get; set; }
        public System.TimeSpan boarding_time { get; set; }
        public System.TimeSpan drop_time { get; set; }
        public int days_of_running { get; set; }
        public Nullable<int> train_numberID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
    }
}
