//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Reservation_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OTRSEntities : DbContext
    {
        public OTRSEntities()
            : base("name=OTRSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<login_> login_ { get; set; }
        public virtual DbSet<tbl_train> tbl_train { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<user> users { get; set; }
    
        public virtual int addbooking(string train_number, Nullable<int> number_of_seats, string user_name, Nullable<long> user_phone_number, string user_email, Nullable<decimal> total_price)
        {
            var train_numberParameter = train_number != null ?
                new ObjectParameter("train_number", train_number) :
                new ObjectParameter("train_number", typeof(string));
    
            var number_of_seatsParameter = number_of_seats.HasValue ?
                new ObjectParameter("number_of_seats", number_of_seats) :
                new ObjectParameter("number_of_seats", typeof(int));
    
            var user_nameParameter = user_name != null ?
                new ObjectParameter("user_name", user_name) :
                new ObjectParameter("user_name", typeof(string));
    
            var user_phone_numberParameter = user_phone_number.HasValue ?
                new ObjectParameter("user_phone_number", user_phone_number) :
                new ObjectParameter("user_phone_number", typeof(long));
    
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var total_priceParameter = total_price.HasValue ?
                new ObjectParameter("total_price", total_price) :
                new ObjectParameter("total_price", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addbooking", train_numberParameter, number_of_seatsParameter, user_nameParameter, user_phone_numberParameter, user_emailParameter, total_priceParameter);
        }
    
        public virtual int addusers(string user_name, string user_email, string user_password, string user_confirm_password, Nullable<System.DateTime> user_dob, string user_location, Nullable<bool> user_status)
        {
            var user_nameParameter = user_name != null ?
                new ObjectParameter("user_name", user_name) :
                new ObjectParameter("user_name", typeof(string));
    
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var user_passwordParameter = user_password != null ?
                new ObjectParameter("user_password", user_password) :
                new ObjectParameter("user_password", typeof(string));
    
            var user_confirm_passwordParameter = user_confirm_password != null ?
                new ObjectParameter("user_confirm_password", user_confirm_password) :
                new ObjectParameter("user_confirm_password", typeof(string));
    
            var user_dobParameter = user_dob.HasValue ?
                new ObjectParameter("user_dob", user_dob) :
                new ObjectParameter("user_dob", typeof(System.DateTime));
    
            var user_locationParameter = user_location != null ?
                new ObjectParameter("user_location", user_location) :
                new ObjectParameter("user_location", typeof(string));
    
            var user_statusParameter = user_status.HasValue ?
                new ObjectParameter("user_status", user_status) :
                new ObjectParameter("user_status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addusers", user_nameParameter, user_emailParameter, user_passwordParameter, user_confirm_passwordParameter, user_dobParameter, user_locationParameter, user_statusParameter);
        }
    
        public virtual int deletebooking(string user_name)
        {
            var user_nameParameter = user_name != null ?
                new ObjectParameter("user_name", user_name) :
                new ObjectParameter("user_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletebooking", user_nameParameter);
        }
    
        public virtual int deletetrains(string train_number)
        {
            var train_numberParameter = train_number != null ?
                new ObjectParameter("train_number", train_number) :
                new ObjectParameter("train_number", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletetrains", train_numberParameter);
        }
    
        public virtual int deleteusers(string user_name)
        {
            var user_nameParameter = user_name != null ?
                new ObjectParameter("user_name", user_name) :
                new ObjectParameter("user_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteusers", user_nameParameter);
        }
    
        public virtual int updatetrain_status(string train_number, string train_status)
        {
            var train_numberParameter = train_number != null ?
                new ObjectParameter("train_number", train_number) :
                new ObjectParameter("train_number", typeof(string));
    
            var train_statusParameter = train_status != null ?
                new ObjectParameter("train_status", train_status) :
                new ObjectParameter("train_status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatetrain_status", train_numberParameter, train_statusParameter);
        }
    
        public virtual int updateusers(string user_name, string user_email, string user_password, string user_confirm_password, Nullable<System.DateTime> user_dob, string user_location, Nullable<bool> user_status)
        {
            var user_nameParameter = user_name != null ?
                new ObjectParameter("user_name", user_name) :
                new ObjectParameter("user_name", typeof(string));
    
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var user_passwordParameter = user_password != null ?
                new ObjectParameter("user_password", user_password) :
                new ObjectParameter("user_password", typeof(string));
    
            var user_confirm_passwordParameter = user_confirm_password != null ?
                new ObjectParameter("user_confirm_password", user_confirm_password) :
                new ObjectParameter("user_confirm_password", typeof(string));
    
            var user_dobParameter = user_dob.HasValue ?
                new ObjectParameter("user_dob", user_dob) :
                new ObjectParameter("user_dob", typeof(System.DateTime));
    
            var user_locationParameter = user_location != null ?
                new ObjectParameter("user_location", user_location) :
                new ObjectParameter("user_location", typeof(string));
    
            var user_statusParameter = user_status.HasValue ?
                new ObjectParameter("user_status", user_status) :
                new ObjectParameter("user_status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateusers", user_nameParameter, user_emailParameter, user_passwordParameter, user_confirm_passwordParameter, user_dobParameter, user_locationParameter, user_statusParameter);
        }
    
        public virtual ObjectResult<viewbooking_Result> viewbooking(string user_name)
        {
            var user_nameParameter = user_name != null ?
                new ObjectParameter("user_name", user_name) :
                new ObjectParameter("user_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewbooking_Result>("viewbooking", user_nameParameter);
        }
    
        public virtual ObjectResult<viewusers_Result> viewusers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewusers_Result>("viewusers");
        }
    
        public virtual ObjectResult<AddUser_Result> AddUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AddUser_Result>("AddUser");
        }
    
        public virtual ObjectResult<AddUserDetail_Result> AddUserDetail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AddUserDetail_Result>("AddUserDetail");
        }
    
        public virtual ObjectResult<Nullable<int>> authenticateusers(string user_email, string user_password)
        {
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var user_passwordParameter = user_password != null ?
                new ObjectParameter("user_password", user_password) :
                new ObjectParameter("user_password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("authenticateusers", user_emailParameter, user_passwordParameter);
        }
    
        public virtual ObjectResult<AddTrain_Result> AddTrain()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AddTrain_Result>("AddTrain");
        }
    
        public virtual int addtrains(string train_number, string train_name, string train_status, Nullable<decimal> ticket_price, Nullable<int> total_seats, Nullable<int> seats_available, string boarding_location, string drop_location, Nullable<System.DateTime> boarding_date, Nullable<System.DateTime> drop_date, Nullable<System.TimeSpan> boarding_time, Nullable<System.TimeSpan> drop_time, Nullable<int> days_of_running)
        {
            var train_numberParameter = train_number != null ?
                new ObjectParameter("train_number", train_number) :
                new ObjectParameter("train_number", typeof(string));
    
            var train_nameParameter = train_name != null ?
                new ObjectParameter("train_name", train_name) :
                new ObjectParameter("train_name", typeof(string));
    
            var train_statusParameter = train_status != null ?
                new ObjectParameter("train_status", train_status) :
                new ObjectParameter("train_status", typeof(string));
    
            var ticket_priceParameter = ticket_price.HasValue ?
                new ObjectParameter("ticket_price", ticket_price) :
                new ObjectParameter("ticket_price", typeof(decimal));
    
            var total_seatsParameter = total_seats.HasValue ?
                new ObjectParameter("total_seats", total_seats) :
                new ObjectParameter("total_seats", typeof(int));
    
            var seats_availableParameter = seats_available.HasValue ?
                new ObjectParameter("seats_available", seats_available) :
                new ObjectParameter("seats_available", typeof(int));
    
            var boarding_locationParameter = boarding_location != null ?
                new ObjectParameter("boarding_location", boarding_location) :
                new ObjectParameter("boarding_location", typeof(string));
    
            var drop_locationParameter = drop_location != null ?
                new ObjectParameter("drop_location", drop_location) :
                new ObjectParameter("drop_location", typeof(string));
    
            var boarding_dateParameter = boarding_date.HasValue ?
                new ObjectParameter("boarding_date", boarding_date) :
                new ObjectParameter("boarding_date", typeof(System.DateTime));
    
            var drop_dateParameter = drop_date.HasValue ?
                new ObjectParameter("drop_date", drop_date) :
                new ObjectParameter("drop_date", typeof(System.DateTime));
    
            var boarding_timeParameter = boarding_time.HasValue ?
                new ObjectParameter("boarding_time", boarding_time) :
                new ObjectParameter("boarding_time", typeof(System.TimeSpan));
    
            var drop_timeParameter = drop_time.HasValue ?
                new ObjectParameter("drop_time", drop_time) :
                new ObjectParameter("drop_time", typeof(System.TimeSpan));
    
            var days_of_runningParameter = days_of_running.HasValue ?
                new ObjectParameter("days_of_running", days_of_running) :
                new ObjectParameter("days_of_running", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addtrains", train_numberParameter, train_nameParameter, train_statusParameter, ticket_priceParameter, total_seatsParameter, seats_availableParameter, boarding_locationParameter, drop_locationParameter, boarding_dateParameter, drop_dateParameter, boarding_timeParameter, drop_timeParameter, days_of_runningParameter);
        }
    
        public virtual ObjectResult<searchtrains_Result> searchtrains(string boarding_location, string drop_location, Nullable<System.DateTime> boarding_date)
        {
            var boarding_locationParameter = boarding_location != null ?
                new ObjectParameter("boarding_location", boarding_location) :
                new ObjectParameter("boarding_location", typeof(string));
    
            var drop_locationParameter = drop_location != null ?
                new ObjectParameter("drop_location", drop_location) :
                new ObjectParameter("drop_location", typeof(string));
    
            var boarding_dateParameter = boarding_date.HasValue ?
                new ObjectParameter("boarding_date", boarding_date) :
                new ObjectParameter("boarding_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<searchtrains_Result>("searchtrains", boarding_locationParameter, drop_locationParameter, boarding_dateParameter);
        }
    
        public virtual ObjectResult<GetTrain_Result> GetTrain(Nullable<int> train_number)
        {
            var train_numberParameter = train_number.HasValue ?
                new ObjectParameter("train_number", train_number) :
                new ObjectParameter("train_number", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTrain_Result>("GetTrain", train_numberParameter);
        }
    
        public virtual ObjectResult<sp_View_Ticket_Result> sp_View_Ticket(Nullable<int> train_number)
        {
            var train_numberParameter = train_number.HasValue ?
                new ObjectParameter("train_number", train_number) :
                new ObjectParameter("train_number", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_View_Ticket_Result>("sp_View_Ticket", train_numberParameter);
        }
    }
}
