//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Reservation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public string user_password { get; set; }
        public string user_confirm_password { get; set; }
        public System.DateTime user_dob { get; set; }
        public string user_location { get; set; }
        public Nullable<bool> user_status { get; set; }
        public Nullable<int> train_number { get; set; }
        public Nullable<int> booking_id { get; set; }
    
        public virtual booking booking { get; set; }
        public virtual tbl_train tbl_train { get; set; }
    }
}
